// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: spotify

#include "ui.h"

// COMPONENT song_name_picture

lv_obj_t * ui_song_name_picture_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_song_name_picture;
    cui_song_name_picture = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_song_name_picture, 784);
    lv_obj_set_height(cui_song_name_picture, 252);
    lv_obj_set_x(cui_song_name_picture, 0);
    lv_obj_set_y(cui_song_name_picture, -104);
    lv_obj_set_align(cui_song_name_picture, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_song_name_picture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SONG_NAME_PICTURE_NUM);
    children[UI_COMP_SONG_NAME_PICTURE_SONG_NAME_PICTURE] = cui_song_name_picture;
    lv_obj_add_event_cb(cui_song_name_picture, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_song_name_picture, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_song_name_picture_create_hook(cui_song_name_picture);
    return cui_song_name_picture;
}

