// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: spotify

#ifndef _UI_COMP_SONG_NAME_PICTURE_H
#define _UI_COMP_SONG_NAME_PICTURE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT song_name_picture
#define UI_COMP_SONG_NAME_PICTURE_SONG_NAME_PICTURE 0
#define _UI_COMP_SONG_NAME_PICTURE_NUM 1
lv_obj_t * ui_song_name_picture_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
