// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: spotify

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TOP_BAR = NULL;
lv_obj_t * ui_TIME = NULL;
lv_obj_t * ui_DATE = NULL;
lv_obj_t * ui_ARTIST_SONG = NULL;
lv_obj_t * ui_ARTIST_NAME1 = NULL;
lv_obj_t * ui_CURR_TIME = NULL;
lv_obj_t * ui_END_TIME = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_PLAYING_DEVICE = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_shufflegreen = NULL;
lv_obj_t * ui_shuffleblack = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TOP_BAR = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TOP_BAR, 240);
    lv_obj_set_height(ui_TOP_BAR, 20);
    lv_obj_set_x(ui_TOP_BAR, 0);
    lv_obj_set_y(ui_TOP_BAR, -150);
    lv_obj_set_align(ui_TOP_BAR, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TOP_BAR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TOP_BAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TIME, -84);
    lv_obj_set_y(ui_TIME, -150);
    lv_obj_set_align(ui_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIME, "00:00 PM");

    ui_DATE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DATE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DATE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DATE, 70);
    lv_obj_set_y(ui_DATE, -150);
    lv_obj_set_align(ui_DATE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DATE, "MM/DD/YYYY");

    ui_ARTIST_SONG = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ARTIST_SONG, 240);
    lv_obj_set_height(ui_ARTIST_SONG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ARTIST_SONG, 1);
    lv_obj_set_y(ui_ARTIST_SONG, -111);
    lv_obj_set_align(ui_ARTIST_SONG, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_ARTIST_SONG, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ARTIST_SONG, "ARTIST SONG");
    lv_obj_set_style_text_align(ui_ARTIST_SONG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ARTIST_NAME1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ARTIST_NAME1, 240);
    lv_obj_set_height(ui_ARTIST_NAME1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ARTIST_NAME1, 0);
    lv_obj_set_y(ui_ARTIST_NAME1, 65);
    lv_obj_set_align(ui_ARTIST_NAME1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ARTIST_NAME1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ARTIST_NAME1, "ARTIST NAME");
    lv_obj_set_style_text_align(ui_ARTIST_NAME1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CURR_TIME = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CURR_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CURR_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CURR_TIME, -95);
    lv_obj_set_y(ui_CURR_TIME, 110);
    lv_obj_set_align(ui_CURR_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CURR_TIME, "CURR");

    ui_END_TIME = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_END_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_END_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_END_TIME, 98);
    lv_obj_set_y(ui_END_TIME, 110);
    lv_obj_set_align(ui_END_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_END_TIME, "END");

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 218);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, -1);
    lv_obj_set_y(ui_Bar1, 88);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 235);
    lv_obj_set_height(ui_Panel2, 27);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, 141);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x1CD24D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_719776243);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image2, -102);
    lv_obj_set_y(ui_Image2, 141);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PLAYING_DEVICE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PLAYING_DEVICE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PLAYING_DEVICE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PLAYING_DEVICE, -42);
    lv_obj_set_y(ui_PLAYING_DEVICE, 142);
    lv_obj_set_align(ui_PLAYING_DEVICE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PLAYING_DEVICE, "PLAYING ON ");

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_1011443021);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -56);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_shufflegreen = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_shufflegreen, &ui_img_shuffle_green_20_20_png);
    lv_obj_set_width(ui_shufflegreen, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_shufflegreen, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_shufflegreen, -58);
    lv_obj_set_y(ui_shufflegreen, 110);
    lv_obj_set_align(ui_shufflegreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shufflegreen, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_shufflegreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_shufflegreen, 400);

    ui_shuffleblack = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_shuffleblack, &ui_img_shuffle_black_20_20_png);
    lv_obj_set_width(ui_shuffleblack, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_shuffleblack, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_shuffleblack, -58);
    lv_obj_set_y(ui_shuffleblack, 110);
    lv_obj_set_align(ui_shuffleblack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shuffleblack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_shuffleblack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_shuffleblack, 400);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TOP_BAR = NULL;
    ui_TIME = NULL;
    ui_DATE = NULL;
    ui_ARTIST_SONG = NULL;
    ui_ARTIST_NAME1 = NULL;
    ui_CURR_TIME = NULL;
    ui_END_TIME = NULL;
    ui_Bar1 = NULL;
    ui_Panel2 = NULL;
    ui_Image2 = NULL;
    ui_PLAYING_DEVICE = NULL;
    ui_Image3 = NULL;
    ui_shufflegreen = NULL;
    ui_shuffleblack = NULL;

}
