// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: spotify

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TOP_BAR;
extern lv_obj_t * ui_TIME;
extern lv_obj_t * ui_DATE;
extern lv_obj_t * ui_ARTIST_SONG;
extern lv_obj_t * ui_ARTIST_NAME1;
extern lv_obj_t * ui_CURR_TIME;
extern lv_obj_t * ui_END_TIME;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_PLAYING_DEVICE;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_shufflegreen;
extern lv_obj_t * ui_shuffleblack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

